version: '3'
services:
  postgres:
    image: postgres
    ports:
    - 5432:5432
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=watchlistadb
  server:
    build: ./
    command: sh -c "npm install && npm run knex:migrate:latest && npm run dev"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/watchlistadb
    ports:
      - '5000:5000'
      - '8080:8080'
    working_dir: /home/app
